replicaCount: 1

image:
  repository: task-management-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: tasks.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: JAVA_OPTS
    value: "-Xmx1024m -Xms512m"

mysql:
  enabled: true
  auth:
    rootPassword: root
    username: tasks
    password: tasks123
    database: tasks
  primary:
    persistence:
      enabled: true
      size: 8Gi

configMap:
  config.yml: |
    database:
      driverClass: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://{{ .Release.Name }}-mysql:3306/tasks
      user: tasks
      password: tasks123
      maxWaitForConnection: 1s
      validationQuery: "SELECT 1"
      minSize: 8
      maxSize: 32
    
    server:
      type: simple
      applicationContextPath: /
      adminContextPath: /admin
      connector:
        type: http
        port: 8080
    
    logging:
      level: INFO
      loggers:
        com.example.tasks: DEBUG
        org.jdbi: DEBUG
      appenders:
        - type: console
          threshold: ALL
          target: stdout